import Head from "next/head";

import MainCard, { MainCardProps } from "../components/MainCard";

import PlaceCard from "../components/PlaceCard";
import { PlaceCardType } from "../interfaces";
import api from "../services/axios";
import styles from "../styles/Home.module.css";

export default async function Page() {
  let places: PlaceCardType[] = [];
  try {
    const { data } = await api.get("api/places/cards");
    if (!!data.erro || !data.data) throw data.error;
    places = data.data || [];
    console.log(places);
  } catch (error) {
    places = [];
    console.log("error");
  }

  const mainCardData = {
    imageUrl:
      "https://fqgiwjnywbpxoliwncof.supabase.co/storage/v1/object/public/valtech/others/asdasd%20(2).png",
    mainTitle: "Valtech_",
    topTitle: "Front-end",
    buttonText: "Get in touch",
    message:
      "Complexity, uncertainty and rapid technological change have transformed the business landscape. Historical performance is an unreliable indicator of future success and the way we connect to each other matters. The way we learn matters. ",
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Valtech Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.fill}>
          <MainCard {...mainCardData} />
        </div>
        {places.length > 0 ? (
          places.map((item, index) => (
            <div
              key={item.id}
              className={
                index === 0
                  ? styles.square
                  : index === 5
                  ? `${styles.square} ${styles.last}`
                  : ""
              }
            >
              <PlaceCard {...item} />
            </div>
          ))
        ) : (
          <div> Could not load data...</div>
        )}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://github.com/lucarampi/valtech-challenge"
          target="_blank"
          rel="noreferrer"
        >
          Developed by <span className={styles.logo}>Luca A.R.</span>
        </a>
      </footer>
    </div>
  );
}

// export async function getServerSideProps() {

//   return {
//     props: { places }, // will be passed to the page component as props
//   };
// }
