import Head from "next/head";

import PlaceCard from "../components/PlaceCard";
import PlaceCardType from "../interfaces";
import api from "../services/axios";
import styles from "../styles/Home.module.css";

interface HomeProps {
  places: PlaceCardType[];
}

export default function Home({ places }: HomeProps) {
  console.log(places);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {places.map((item, index) => (
          <div
            key={item.id}
            className={
              index === 0
                ? styles.square
                : index === 5
                ? `${styles.square} ${styles.last}`
                : ""
            }
          >
            <PlaceCard {...item} />
          </div>
        ))}
        {/*       
        
        <div className={styles.square}>
          <PlaceCard {...places[0]} />
        </div>
        <div className={styles.rectangle}>
          <PlaceCard {...places[0]} />
        </div>
        <div className={styles.rectangle}>
          <PlaceCard
            buttonText="explore more"
            mainTitle="valtech_"
            topTitle="front-end"
            message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
          />
        </div>
        <div className={`${styles.square} ${styles.last}`}>
          <PlaceCard
            buttonText="explore more"
            mainTitle="FIRST"
            topTitle="front-end"
            message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
          />
        </div>
        <div className={styles.rectangle}>
          <PlaceCard
            buttonText="explore more"
            mainTitle="valtech_"
            topTitle="front-end"
            message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
          />
        </div>
        <div className={styles.rectangle}>
          <PlaceCard
            buttonText="explore more"
            mainTitle="valtech_"
            topTitle="front-end"
            message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
          />
        </div> */}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by <span className={styles.logo}>Luca A.R.</span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  let places = [];
  const { data } = await api.get("api/places/cards");
  if (!!data) places = data.data;
  console.log(places);
  return {
    props: { places }, // will be passed to the page component as props
  };
}
