import Head from "next/head";
import MainCard from "../components/MainCard";
import PlaceCard from "../components/PlaceCard";
import api from "../services/axios";
import styles from "../styles/Home.module.css";

export default async function Home() {
  let places = []
  const { data } = await api.get("api/places/cards");
  if (!!data) places = data.data
  console.log(places)

    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.fill}>
            <PlaceCard
              buttonText="explore more"
              mainTitle="valtech_"
              topTitle="front-end"
              message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
            />
          </div>
          <div className={styles.square}>
            <PlaceCard
              buttonText="explore more"
              mainTitle="valtech_"
              topTitle="front-end"
              message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
            />
          </div>
          <div className={styles.rectangle}>
            <PlaceCard
              buttonText="explore more"
              mainTitle="valtech_"
              topTitle="front-end"
              message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
            />
          </div>
          <div className={styles.rectangle}>
            <PlaceCard
              buttonText="explore more"
              mainTitle="valtech_"
              topTitle="front-end"
              message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
            />
          </div>
          <div className={`${styles.square} ${styles.last}`}>
            <PlaceCard
              buttonText="explore more"
              mainTitle="FIRST"
              topTitle="front-end"
              message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
            />
          </div>
          <div className={styles.rectangle}>
            <PlaceCard
              buttonText="explore more"
              mainTitle="valtech_"
              topTitle="front-end"
              message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
            />
          </div>
          <div className={styles.rectangle}>
            <PlaceCard
              buttonText="explore more"
              mainTitle="valtech_"
              topTitle="front-end"
              message="Venice, the capital of the northen Italy's Veneto region, is built on more  than 100 small islands ia a lagoon in de Adriatic Sea. It has no roads, just canals"
            />
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Developed by <span className={styles.logo}>Luca A.R.</span>
          </a>
        </footer>
      </div>
    );
}
